### PR TITLE
Comparison of semsim and LLM embeds

### PR DESCRIPTION
**Pull request by caufieldjh**

### CODE REVIEW

**Comment by matentzn** [comment]
Cc @souzadevinicius

**Comment by cmungall** [comment]
should this go in a different repo?

**Comment by caufieldjh** [comment]
It may be appropriate in https://github.com/monarch-initiative/ontogpt-experiments

**Comment by caufieldjh** [comment]
Thanks for bumping this - Going to move to [ontogpt-experiments](https://github.com/monarch-initiative/ontogpt-experiments)

**Pull request closed without merging**
