### PR TITLE
Update to latest SSSOM(v0.4.x)

### PR DESCRIPTION
**Pull request by hrshdhgd**
- [x] Update `sssom`, `semsimian` and `kgcl-schema` dependency 
- [x] add `linkml` dependency in tox for pytest
- [x] Addresses https://github.com/mapping-commons/sssom-py/issues/441#event-10982549956
  - **Merge this ONLY when `sssom==0.4.0` is released.

Refactors done:

 - ~`from sssom.context import get_default_metadata`~ => `from sssom.constants import get_default_metadata`
 - ~`from sssom.typehints import Metadata`~ => `from sssom.constants import MetadataType`
   - Older `Metadata` had the `metadata` attribute which is now collapsed
     - e.g. `meta: Metadata`
       ```
               mapping_set_id = meta.metadata[MAPPING_SET_ID]
               license = meta.metadata[LICENSE]
       ```
        is now `meta: MetadataType`
       ```
               mapping_set_id = meta[MAPPING_SET_ID]
               license = meta[LICENSE]
       ```
 - ~`doc = MappingSetDocument(prefix_map=metadata[PREFIX_MAP_KEY], mapping_set=mset)`~ 
   - ```
       converter = curies.chain([
          Converter.from_prefix_map(metadata.pop(CURIE_MAP_KEY, {})),
          ensure_converter(prefix_map, use_defaults=False)
      ])
       doc = MappingSetDocument(converter=converter, mapping_set=mset)
      ```
 - ~`metadata = get_metadata_and_prefix_map(MATCHER_META_YML)`~ => `converter, metadata = get_metadata_and_prefix_map(MATCHER_META_YML)`

### CODE REVIEW

**Comment by matentzn** [comment]
Thanks! Looks sane, so far!

**Comment by cthoyt** [comment]
@hrshdhgd did you miss all the effort I put into doing this? https://github.com/INCATools/ontology-access-kit/pull/666

**Comment by hrshdhgd** [comment]
Apparently I did, sorry about that. Should have been mentioned in https://github.com/mapping-commons/sssom-py/issues/441

**Comment by hrshdhgd** [comment]
Duplication of effort with #666 . Closing for that reason.

**Comment by cthoyt** [comment]
> Apparently I did, sorry about that. Should have been mentioned in [mapping-commons/sssom-py#441](https://github.com/mapping-commons/sssom-py/issues/441)

It was - see https://github.com/mapping-commons/sssom-py/issues/441#issuecomment-1814730128

**Pull request closed without merging**
