### PR TITLE
~rustsim~ => semsimian

### PR DESCRIPTION
**Pull request by hrshdhgd**
~rustsim~ => semsimian

`poetry update` and reformatted code.

### CODE REVIEW

**Review by cmungall — APPROVED** [review]

**Review by caufieldjh — CHANGES_REQUESTED** [review]
For consistency, I think the class `RustSimImplementation` should also be changed to `SemsimianImplementation`

**Comment by justaddcoffee** [comment]
> For consistency, I think the class RustSimImplementation should also be changed to SemsimianImplementation

yes, nice catch

**Review by justaddcoffee — APPROVED** [review]

**Review by justaddcoffee — APPROVED** [review]

**Comment by hrshdhgd** [comment]
Done!

**Comment by hrshdhgd** [comment]
@justaddcoffee  and @caufieldjh , do you guys think this will conflict with our existing PR ? If so, let this just be a draft. If not, please merge it. I am out of office all of next week.

**Comment by caufieldjh** [comment]
Yeah, it'll probably conflict. But it's necessary so we'll resolve as needed

**Comment by cmungall** [comment]
looks like @hrshdhgd addressed the desired changes - merge when ready!

**Review by caufieldjh — APPROVED** [review]

**Pull request merged**
