### PR TITLE
add a subset of OAK logos to this repo

### PR DESCRIPTION
**Pull request by nlharris**

### CODE REVIEW

**Review by cmungall — CHANGES_REQUESTED** [review]
looks like the logos went in at the top level?

**Comment by nlharris** [comment]
ugh, sorry. i'm not actually sure how to move them from this PR (it won't let me edit them) so maybe we should just merge this and then i'll do another pr to move them?

**Comment by cmungall** [comment]
sounds good!

**Comment by nlharris** [comment]
couldn't find a way to move them via github; had to add them to the correct folder and then, separately, delete from the main folder.

**Pull request merged**
