### PR TITLE
Fix slug in benchmark target in Makefile (rustsim: -> semsimian)

### PR DESCRIPTION
**Pull request by justaddcoffee**

### CODE REVIEW

**Review by cmungall — APPROVED** [review]
I'm not totally sure we should be doing benchmarks in the Makefile in the first place but I assume this is temporary...

**Comment by justaddcoffee** [comment]
> I'm not totally sure we should be doing benchmarks in the Makefile in the first place but I assume this is temporary...

Well, we were not sure where else to put it - it doesn't seem crazy to have a target for benchmarking IMHO. Glad to move it though - where would be a better place?

**Comment by caufieldjh** [comment]
We could also make these optional tests (but definitely optional since they, especially #578, are time-instensive)

**Comment by cmungall** [comment]
I think ultimately these belong in pheval, but for now I would suggest having a separate subfolder with its own Makefile. But OK to merge for now

**Pull request merged**
