### PR TITLE
Added change handler for `kgcl.RemoveNodeFromSubset`

### PR DESCRIPTION
**Pull request by hrshdhgd**
Previously non existent. 

Triggered by: https://github.com/monarch-initiative/mondo/pull/7962#pullrequestreview-2192964282

### CODE REVIEW

**Review by sierra-moxon — APPROVED** [review]
I like the neat set + list comprehension here!  

Tiny request: adding the expected type to the `value` method parameter would help me understand.  Alternatively, a test to exercise it.

**Comment by hrshdhgd** [comment]
Thank you @sierra-moxon ! Working on it now..

**Review by sierra-moxon — APPROVED** [review]
Thanks Harshad!! :)

**Comment by hrshdhgd** [comment]
Thank you!!!

**Pull request merged**
