### PR TITLE
Add codespell support: config, action (to detect new) + get some typos fixed

### PR DESCRIPTION
**Pull request by yarikoptic**

### CODE REVIEW

**Comment by cmungall** [comment]
I approved the build and also invited you to the repo so this should not be necessary in future, thx!

**Comment by yarikoptic** [comment]
cool, thanks - accepted. new typos emerged since then, rebased, added an ignore on "infarctions" (not so common word) and reran.

**Comment by cmungall** [comment]
I rebased, this introduced a new test file that fails spellchecks. I think in this scenario we want to exclude verbatim test examples like this

**Comment by yarikoptic** [comment]
I did before fixed up those

```
❯ git diff origin/main --stat -- ./tests/input
 tests/input/AMPK-Signaling.cx   |      2 +-
 tests/input/go-nucleus.owl      |      8 +-
 tests/input/ncbigene-1956.xml   | 635814 ++++++++++++++++++++++++++++++++
 tests/input/uniprot-P12345.json |   1898 +
 4 files changed, 637717 insertions(+), 5 deletions(-)
```
I can exclude them all -- I just wonder if that anyhow would effect tests -- that they would have corrected words while input files -- failed... let me redo that way and see if we hit such cases. Also I will fix a fresh typo in a notebook

**Comment by yarikoptic** [comment]
CI is green, so I guess ignoring the inputs, didn't cause some turmoil in the tests -- good

**Review by cmungall — APPROVED** [review]

**Pull request merged**
