### PR TITLE
Making rustsim a non-extra dependency. 552

### LINKED ISSUE #552: problem installing with latest oaklib 0.5.2
```
✗ ontogpt  enrichment -r sqlite:obo:hgnc  -U tests/input/genesets/sensory-ataxia.yaml
Traceback (most recent call last):
  File "/Users/cjm/Library/Caches/pypoetry/virtualenvs/ontogpt-KHJsTWkT-py3.10/bin/ontogpt", line 3, in <module>
    from ontogpt.cli import main
  File "/Users/cjm/repos/ontogpt/src/ontogpt/cli.py", line 15, in <module>
    from oaklib import get_adapter
  File "/Users/cjm/Library/Caches/pypoetry/virtualenvs/ontogpt-KHJsTWkT-py3.10/lib/python3.10/site-packages/oaklib/__init__.py", line 9, in <module>
    from oaklib.selector import get_adapter, get_implementation_from_shorthand  # noqa:F401
  File "/Users/cjm/Library/Caches/pypoetry/virtualenvs/ontogpt-KHJsTWkT-py3.10/lib/python3.10/site-packages/oaklib/selector.py", line 15, in <module>
    from oaklib.implementations.funowl.funowl_implementation import FunOwlImplementation
  File "/Users/cjm/Library/Caches/pypoetry/virtualenvs/ontogpt-KHJsTWkT-py3.10/lib/python3.10/site-packages/oaklib/implementations/__init__.py", line 39, in <module>
    from oaklib.implementations.rustsim.rustsim_implementation import RustSimImplementation
  File "/Users/cjm/Library/Caches/pypoetry/virtualenvs/ontogpt-KHJsTWkT-py3.10/lib/python3.10/site-packages/oaklib/implementations/rustsim/rustsim_implementation.py", line 10, in <module>
    from rustsim import get_intersection, jaccard_similarity, mrca_and_score
ModuleNotFoundError: No module named 'rustsim'
```

### PR DESCRIPTION
**Pull request by cmungall**
Fixes #552

but we may want a better long term solution

### CODE REVIEW

**Comment by caufieldjh** [comment]
Oh fun, it's the pywin32 error again.
@hrshdhgd , was there a good workaround for that?

**Comment by hrshdhgd** [comment]
`poetry update --only click`

**Comment by cmungall** [comment]
Thanks @hrshdhgd!

[you are meant to be off today!]

when you are back let's make the SOP clearer and document this in CONTRIBUTING.md.

**Comment by cmungall** [comment]
OK, I tried this in dc5f06c337955579a9f5bc3c815215b3eeeebfa7 but it didn't seem to make any pywin changes, let's see if it fares better

if it doesn't work it may be better to force a release out anyway

**Comment by hrshdhgd** [comment]
Also, this PR suggests[ that poetry version 1.4.0 was being used to create the lock file](https://github.com/INCATools/ontology-access-kit/pull/553/files#diff-f53a023eedfa3fbf2925ec7dc76eecdc954ea94b7e47065393dbad519613dc89R1). The lock and toml files seemed to be rolled back to that version instead of using the latest v1.4.2.

**Pull request merged**
