### PR TITLE
Fix py version window & provide minimum scipy version

### LINKED ISSUE #300: Restore gilda test
This was skipped in order to resolve #299, as the gilda test had stopped running on 3.10

### PR DESCRIPTION
**Pull request by hrshdhgd**
This fixes #300 

Problem: By default an older SciPy version (dependency of a dependency) is installed (v1.6.1) which does not play well with python v3.10. So I add it as a direct dependency and anchor it to `>=1.9.1`. On doing that, there is a complain raised stating the project python version compatibility is from 3.9 to 4 but with the scipy version installed it is 3.9 to 3.12. So I set python version window between 3.9 and 3.12 and now everything seems to be okay.

This window will need to be revisited while supporting future version of python.

### CODE REVIEW

**Review by cmungall — CHANGES_REQUESTED** [review]
I don't want to make scipy a dependency of OAK, it's a heavyweight dependency

Note: it's not currently a main dependency, currently gilda is an extra, and scipy is a dependency on that extra

Can we move it to extras?

Alternatively this may be simpler if we make gilda a plugin

**Comment by hrshdhgd** [comment]
Done.

**Review by cmungall — APPROVED** [review]
I'm missing something

Gilda already depends on scipy, no?

The original point was to ensure a minimum version for scipy?

But it passes...

**Comment by hrshdhgd** [comment]
Yes , by mentioning `scipy` before `gilda` , it installs the latest package rather than depending on `gilda` deciding it. For some reason it installed v1.6.1 inspire of v1.91 being the latest version.

**Pull request merged**
