### PR TITLE
Use oaklib.plugins entry point to discover plugins

### PR DESCRIPTION
**Pull request by pkalita-lbl**

### CODE REVIEW

**Comment by pkalita-lbl** [comment]
See also:

* https://github.com/INCATools/oakx-robot/pull/2
* https://github.com/INCATools/oakx-grape/pull/1

**Comment by cthoyt** [comment]
Amazing! I’m so happy that we can deduplicate code for this very common pattern

**Comment by cthoyt** [comment]
Might not hurt to put a documentation link next to this code though

**Comment by pkalita-lbl** [comment]
> Might not hurt to put a documentation link next to this code though

Done

**Review by cmungall — APPROVED** [review]

**Pull request merged**
