### PR TITLE
OBO Compliance suite (replay of 683)

### PR DESCRIPTION
**Pull request by cmungall**
- First pass at oboformat and obographs conformance suite.
- Allow choice of format when exporting OWL. Addung missing features to obo conversion
- lint
- lint
- Lint. Removing prints.
- Added format_utilities.py -- see #687
- adding test failure info
- reconciled dumper changes between branches

### CODE REVIEW

**Comment by cmungall** [comment]
I can't figure out what is going on here.

The tests work locally, github actions seems to be running against something different than what is on the branch

**Review by matentzn — CHANGES_REQUESTED** [review]
This PR is a bit too big to carefully review for me, so I will trust that it wont result in any breaking. However, can you add a section to the OAK docs on "How to test a new OBOgraphs release with OAK"?

I can see the tests in test_obo_format.py, but I cannot easily imagine the recipe.

1. New OBO graphs version for testing available
2. Compile to JAR
3. Compile new ROBOT JAR with that test version of OBO graphs
4. Run...
5. If X then all is well and we can make an OBO graphs release and push it into ROBOT

A recipe like this would be very useful.

There are also two files

tests/input/obo_conf.yaml
tests/input/obojson_conf.yaml

that are generated as part of a local run. Should these be committed or gitignored?

**Comment by cmungall** [comment]
Works for me locally:

```
poetry run pytest tests/test_utilities/test_cross_ontology_diff.py
```

But this fails on actions

**Comment by cmungall** [comment]
Closed in favor of #715

**Pull request closed without merging**
