### PR TITLE
Add discovered plugins to implementation resolver

### LINKED ISSUE #250: get_implementation_class_from_scheme should use discovery method to find resolvers
it used to be the case that plugins can register scheme to class mappings:

e.g

https://github.com/INCATools/oakx-robot/blob/main/src/oakx_robot/__init__.py

upgrading oakx-robot from 0.1.16, it looks like the plugin mechanism is broken

```
======================================================================
ERROR: test_plugin (tests.test_oakx_robot.TestSqlDatabaseImplementation)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/cjm/repos/oakx-robot/tests/test_oakx_robot.py", line 14, in setUp
    self.oi = get_implementation_from_shorthand(f'robot:{TEST_OWL}')
  File "/Users/cjm/Library/Caches/pypoetry/virtualenvs/oakx-robot-u_pCuxHY-py3.9/lib/python3.9/site-packages/oaklib/selector.py", line 81, in get_implementation_from_shorthand
    res = get_resource_from_shorthand(descriptor, format)

  File "/Users/cjm/Library/Caches/pypoetry/virtualenvs/oakx-robot-u_pCuxHY-py3.9/lib/python3.9/site-packages/oaklib/selector.py", line 166, in get_resource_from_shorthand
    impl_class = get_implementation_class_from_scheme(scheme)
  File "/Users/cjm/Library/Caches/pypoetry/virtualenvs/oakx-robot-u_pCuxHY-py3.9/lib/python3.9/site-packages/oaklib/selector.py", line 92, in get_implementation_class_from_scheme
    return implementation_resolver.lookup(scheme)
  File "/Users/cjm/Library/Caches/pypoetry/virtualenvs/oakx-robot-u_pCuxHY-py3.9/lib/python3.9/site-packages/class_resolver/api.py", line 176, in lookup
    return get_cls(
  File "/Users/cjm/Library/Caches/pypoetry/virtualenvs/oakx-robot-u_pCuxHY-py3.9/lib/python3.9/site-packages/class_resolver/api.py", line 378, in get_cls
    raise KeyError(
KeyError: "Invalid OntologyInterface name: robot. Valid choices are: ['abstractsparql', 'agroportal', 'basicontologyinterface', 'bioportal', 'differinterface', 'funowl', 'gilda', 'lov', 'mappingproviderinterface', 'metadatainterface', 'obographinterface', 'obolibrary', 'ols', 'ontobee', 'ontoportalimplementationbase', 'owlinterface', 'patcherinterface', 'pronto', 'prontolib', 'rdfinterface', 'rdflib', 'relationgraphinterface', 'searchinterface', 'semanticsimilarityinterface', 'sparql', 'sql', 'sqlite', 'subsetterinterface', 'textannotatorinterface', 'ubergraph', 'validatorinterface', 'wikidata']"
```

### PR DESCRIPTION
**Pull request by pkalita-lbl**
Fixes #250

### CODE REVIEW

**Comment by cthoyt** [comment]
Plug-in discovery is already implemented in class resolver iirc, you should check there to de duplicate code

**Comment by pkalita-lbl** [comment]
I searched the `class-resolver` documentation, glanced through the code, searched for use of the `importlib` or `pkgutil` modules, and I came up empty. So I'm not sure; if it's there I'm not finding it 😕

**Comment by cthoyt** [comment]
This function allows for directly creating a resolver based on entry points registered in a standard way and accessed via `pkg_resources`: https://class-resolver.readthedocs.io/en/latest/api/class_resolver.BaseResolver.html#class_resolver.BaseResolver.from_entrypoint.  For a pre-existing resolver, you can uses `resolver.register_entrypoint(<name>)` documented at https://class-resolver.readthedocs.io/en/latest/api/class_resolver.BaseResolver.html#class_resolver.BaseResolver.register_entrypoint.

I'll admit the docs aren't so great for this, especially since the inherited functions don't show up in the ClassResolver subclass of BaseResolver

**Comment by pkalita-lbl** [comment]
Haha I guess I didn't find it because I didn't know what I was looking for 😂 And that's mostly because I'm total unfamiliar with this entry point thing. I started to read through [this](https://setuptools.pypa.io/en/latest/pkg_resources.html), and it's certainly interesting. But it also has major implications for the existing OAK plug-in model. I'm sure we want to move toward whatever the most standard way of doing plugins is, but I don't know if we want that to block fixing the bug at hand (#250). @cmungall thoughts?

**Comment by cmungall** [comment]
How about we merge just now so we can restore previously working plugins, then we can continue discussion of the perfect plugin framework on this issue: #171

**Review by cmungall — APPROVED** [review]

**Pull request merged**
